### ISSUE TITLE
DI issues with IRepositoryManager

### ISSUE THREAD

**Issue by AnnaGolosova** [MagzyCode/TechnicalTask#10]
I think that all instance creation logic should be on DI container side.
![image](https://user-images.githubusercontent.com/23430041/162619113-0a313f92-0d8f-48ff-b9b7-4546f5907594.png)

**Comment by MagzyCode** [comment]
![image](https://user-images.githubusercontent.com/59421317/163378421-d7f01d5c-b45a-48e2-a79c-9e5ef9c2589a.png)
![image](https://user-images.githubusercontent.com/59421317/163378492-0a6bd687-bb6f-469c-a0ae-d4decf437463.png)
