### ISSUE TITLE
Behavior error in AddFridgeProduct method

### ISSUE THREAD

**Issue by AnnaGolosova** [MagzyCode/TechnicalTask#8]
When I'm requesting this endpoint, I expect that new product will be added. If a product is already exists, an error should be thrown. 

It can cause an issues if the endpoint is updating some entity when we're not expecting it.

![image](https://user-images.githubusercontent.com/23430041/162618432-27f95b52-02b1-4d9f-ae43-8821ec11f530.png)

**Comment by MagzyCode** [comment]
![image](https://user-images.githubusercontent.com/59421317/163252803-11798839-a365-4cfd-aee3-11a63c89c0e2.png)
